sudo: required
language: node_js
node_js:
  - "8"

branches:
  only:
    - master

services:
  - docker

install:
  - npm install -g @angular/cli
  - npm install

script:
  - npm run-script build

after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - account_id=$(aws sts get-caller-identity --output text --query 'Account')
  - region_id=us-east-1
  - registry_url=${account_id}.dkr.ecr.${region_id}.amazonaws.com/wallet
  - eval $(aws ecr get-login --no-include-email --region ${region_id})
  - docker build -t ${registry_url} .
  - docker push ${registry_url}

